apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp1-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: default
  source:
    path: "newchart"
    repoURL: "git@github.com:Egor-Dragun/argocd.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-app1.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
    